### ISSUE TITLE
git clone error

### ISSUE THREAD

**Issue by smartinsightsfromdata** [hannesmuehleisen/MonetDBLite-Python#11]
I'm on OSX 10.13.3.

Trying to run `git clone https://github.com/hannesmuehleisen/MonetDBLite-Python.git --depth 1 --recursive`

I get an error:

```
Cloning into 'MonetDBLite-Python'...
remote: Counting objects: 45, done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 45 (delta 3), reused 27 (delta 2), pack-reused 0
Unpacking objects: 100% (45/45), done.
Submodule 'src/monetdblite' (https://github.com/hannesmuehleisen/MonetDBLite-C) registered for path 'src/monetdblite'
Cloning into '/Users/e/Dropbox/devlib/gitlib/monet/MonetDBLite-Python/src/monetdblite'...
remote: Counting objects: 476, done.        
remote: Compressing objects: 100% (410/410), done.        
remote: Total 476 (delta 122), reused 92 (delta 65), pack-reused 0        
Receiving objects: 100% (476/476), 2.24 MiB | 3.74 MiB/s, done.
Resolving deltas: 100% (122/122), done.
error: Server does not allow request for unadvertised object 5e5b4e7289d0918e488f6310ada8701ebe61abd7
Fetched in submodule path 'src/monetdblite', but it did not contain 5e5b4e7289d0918e488f6310ada8701ebe61abd7. Direct fetching of that commit failed.
```

Then `python setup.py install` fails:

```
MonetDBLite-Python e$ python setup.py install
cc -DLIBGDK -DLIBMAL -DLIBOPTIMIZER -DLIBSTREAM -Imonetdblite/src/ -Imonetdblite/src/common -Imonetdblite/src/embedded -Imonetdblite/src/gdk -Imonetdblite/src/mal/mal -Imonetdblite/src/mal/modules -Imonetdblite/src/mal/optimizer -Imonetdblite/src/mal/sqlbackend -Imonetdblite/src/sql/include -Imonetdblite/src/sql/common -Imonetdblite/src/sql/server -Imonetdblite/src/sql/storage -Imonetdblite/src/sql/storage/bat -fPIC -I/Users/e/anaconda3/include/python3.6m -I/Users/e/anaconda3/include/python3.6m -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/e/anaconda3/include -arch x86_64 -I/Users/e/anaconda3/include -arch x86_64 -I/Users/e/anaconda3/lib/python3.6/site-packages/numpy/core/include -MMD -MF build/debug/deps/embeddedpy/conversion.d -O0 -g -Wall -Wextra -Wmissing-prototypes -Wold-style-definition  -c embeddedpy/conversion.c -o build/debug/embeddedpy/conversion.o
cc -DLIBGDK -DLIBMAL -DLIBOPTIMIZER -DLIBSTREAM -Imonetdblite/src/ -Imonetdblite/src/common -Imonetdblite/src/embedded -Imonetdblite/src/gdk -Imonetdblite/src/mal/mal -Imonetdblite/src/mal/modules -Imonetdblite/src/mal/optimizer -Imonetdblite/src/mal/sqlbackend -Imonetdblite/src/sql/include -Imonetdblite/src/sql/common -Imonetdblite/src/sql/server -Imonetdblite/src/sql/storage -Imonetdblite/src/sql/storage/bat -fPIC -I/Users/e/anaconda3/include/python3.6m -I/Users/e/anaconda3/include/python3.6m -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/e/anaconda3/include -arch x86_64 -I/Users/e/anaconda3/include -arch x86_64 -I/Users/e/anaconda3/lib/python3.6/site-packages/numpy/core/include -MMD -MF build/debug/deps/embeddedpy/embeddedpy.d -O0 -g -Wall -Wextra -Wmissing-prototypes -Wold-style-definition  -c embeddedpy/embeddedpy.c -o build/debug/embeddedpy/embeddedpy.o
cc -DLIBGDK -DLIBMAL -DLIBOPTIMIZER -DLIBSTREAM -Imonetdblite/src/ -Imonetdblite/src/common -Imonetdblite/src/embedded -Imonetdblite/src/gdk -Imonetdblite/src/mal/mal -Imonetdblite/src/mal/modules -Imonetdblite/src/mal/optimizer -Imonetdblite/src/mal/sqlbackend -Imonetdblite/src/sql/include -Imonetdblite/src/sql/common -Imonetdblite/src/sql/server -Imonetdblite/src/sql/storage -Imonetdblite/src/sql/storage/bat -fPIC -I/Users/e/anaconda3/include/python3.6m -I/Users/e/anaconda3/include/python3.6m -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/e/anaconda3/include -arch x86_64 -I/Users/e/anaconda3/include -arch x86_64 -I/Users/e/anaconda3/lib/python3.6/site-packages/numpy/core/include -MMD -MF build/debug/deps/embeddedpy/pytypes.d -O0 -g -Wall -Wextra -Wmissing-prototypes -Wold-style-definition  -c embeddedpy/pytypes.c -o build/debug/embeddedpy/pytypes.o
cc -DLIBGDK -DLIBMAL -DLIBOPTIMIZER -DLIBSTREAM -Imonetdblite/src/ -Imonetdblite/src/common -Imonetdblite/src/embedded -Imonetdblite/src/gdk -Imonetdblite/src/mal/mal -Imonetdblite/src/mal/modules -Imonetdblite/src/mal/optimizer -Imonetdblite/src/mal/sqlbackend -Imonetdblite/src/sql/include -Imonetdblite/src/sql/common -Imonetdblite/src/sql/server -Imonetdblite/src/sql/storage -Imonetdblite/src/sql/storage/bat -fPIC -I/Users/e/anaconda3/include/python3.6m -I/Users/e/anaconda3/include/python3.6m -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/e/anaconda3/include -arch x86_64 -I/Users/e/anaconda3/include -arch x86_64 -I/Users/e/anaconda3/lib/python3.6/site-packages/numpy/core/include -MMD -MF build/debug/deps/embeddedpy/type_conversion.d -O0 -g -Wall -Wextra -Wmissing-prototypes -Wold-style-definition  -c embeddedpy/type_conversion.c -o build/debug/embeddedpy/type_conversion.o
cc -DLIBGDK -DLIBMAL -DLIBOPTIMIZER -DLIBSTREAM -Imonetdblite/src/ -Imonetdblite/src/common -Imonetdblite/src/embedded -Imonetdblite/src/gdk -Imonetdblite/src/mal/mal -Imonetdblite/src/mal/modules -Imonetdblite/src/mal/optimizer -Imonetdblite/src/mal/sqlbackend -Imonetdblite/src/sql/include -Imonetdblite/src/sql/common -Imonetdblite/src/sql/server -Imonetdblite/src/sql/storage -Imonetdblite/src/sql/storage/bat -fPIC -I/Users/e/anaconda3/include/python3.6m -I/Users/e/anaconda3/include/python3.6m -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/e/anaconda3/include -arch x86_64 -I/Users/e/anaconda3/include -arch x86_64 -I/Users/e/anaconda3/lib/python3.6/site-packages/numpy/core/include -MMD -MF build/debug/deps/embeddedpy/unicode.d -O0 -g -Wall -Wextra -Wmissing-prototypes -Wold-style-definition  -c embeddedpy/unicode.c -o build/debug/embeddedpy/unicode.o
Traceback (most recent call last):
  File "setup.py", line 68, in <module>
    (error.decode('utf8') if PY3 else error)))
Exception: Failed to compile MonetDBLite sources: make: *** No rule to make target `build/debug/monetdblite/common/stream.o', needed by `all'.  Stop.
make: *** Waiting for unfinished jobs....
In file included from embeddedpy/embeddedpy.cIn file included from :13:
embeddedpy/conversion.cIn file included from :embeddedpy/embeddedpy.h2::
In file included from embeddedpy/conversion.h17::
17:
embeddedpy/pyheader.h:19:embeddedpy/pyheader.h10:19: fatal error:: 10:'monetdb_config.h' file not found 
fatal error: 'monetdb_config.h' file not found
#include "monetdb_config.h"
         ^~~~~~~~~~~~~~~~~~
#include "monetdb_config.h"
         ^~~~~~~~~~~~~~~~~~
In file included from embeddedpy/type_conversion.c:9:
In file included from embeddedpy/type_conversion.h:20:
embeddedpy/pyheader.h:19:10: fatal error: 'monetdb_config.h' file not found
#include "monetdb_config.h"
         ^~~~~~~~~~~~~~~~~~
In file included from embeddedpy/pytypes.c:2:
In file included from embeddedpy/pytypes.h:20:
embeddedpy/pyheader.h:19:10: fatal error: 'monetdb_config.h' file not found
#include "monetdb_config.h"
         ^~~~~~~~~~~~~~~~~~
In file included from embeddedpy/unicode.c:9:
In file included from embeddedpy/unicode.h:21:
embeddedpy/pyheader.h:19:10: fatal error: 'monetdb_config.h' file not found
#include "monetdb_config.h"
         ^~~~~~~~~~~~~~~~~~
1 error generated.
1 error generated.
1 error generated.
1 error generated.
make: *** [build/debug/embeddedpy/unicode.o] Error 1
make: *** [build/debug/embeddedpy/pytypes.o] Error 1
make: *** [build/debug/embeddedpy/type_conversion.o] Error 1
make: *** [build/debug/embeddedpy/embeddedpy.o] Error 1
1 error generated.
make: *** [build/debug/embeddedpy/conversion.o] Error 1
```

**Comment by hannesmuehleisen** [comment]
Please try again, I have pushed a bump

**Comment by smartinsightsfromdata** [comment]
@hannesmuehleisen It resolved the git issue. 

But after `python setup.py install` I still get `Segmentation fault: 11`:

```
e$ python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import monetdblite
Segmentation fault: 11
emac:MonetDBLite-Python e$
```

**Comment by hannesmuehleisen** [comment]
I think this is still the issue with anaconda we had before no?

**Comment by hannesmuehleisen** [comment]
this one https://github.com/hannesmuehleisen/MonetDBLite-Python/issues/9

**Comment by smartinsightsfromdata** [comment]
yes - still there.  Now I'm using miniconda but it is the same behaviour.
